export const SEND_OTP = 'SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const CREATE_USER = 'CREATE_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const SET_MOBILE_NUMBER_VERIFIED = 'SET_MOBILE_NUMBER_VERIFIED';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const CHECK_EXPIRE_TIME = 'CHECK_EXPIRE_TIME';
export const SET_LIKES = 'SET_LIKES';
export const SET_UNLINKES = 'SET_UNLINKES';
export const SET_COMMENT = 'SET_COMMENT';
export const SET_THREADS = 'SET_THREADS';
export const TOGGLE_LIKES = 'TOGGLE_LIKES';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const SET_COMMENT_TEXT = 'SET_COMMENT_TEXT';
export const ADD_THREADS = 'ADD_THREADS';
export const USER_PROFILE = 'USER_PROFILE';
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_FOLLOWING_USER = 'GET_FOLLOWING_USER';
export const GET_FOLLOWER_USER = 'GET_FOLLOWER_USER';
export const GET_JOINED_COMMUNITY = 'JOINED_COMMUNITY';
export const GET_COMMUNITY = 'GET_COMMUNITY';
export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const ADD_JOINED_COMMUNITY = 'GET_JOINED_COMMUNITY';
export const SET_PROFILE_AVATAR = 'SET_PROFILE_AVATAR';
export const SET_EDIT_FULL_NAME = 'SET_EDIT_FULL_NAME';
export const SET_EDIT_DESCRIPTION = 'SET_EDIT_DESCRIPTION';
export const GET_PROFILE = 'GET_PROFILE';
//added create new community
//added match score
export const GET_CRICKET_MATCHES = 'GET_CRICKET_MATCHES';
export const GET_FOOTBALL_MATCHES = 'GET_FOOTBALL_MATCHES';
export const GET_CRICKET_PLAYER_SCORE = 'GET_CRICKET_PLAYER_SCORE';
export const GET_FOOTBALLL_PLAYER_SCORE = 'GET_FOOTBALLL_PLAYER_SCORE';
export const ADD_FOOTBALL_MATCHES = 'ADD_FOOTBALL_SCORE';
export const ADD_CRICKET_MATCHES = 'ADD_FOOTBALL_SCORE';
export const ADD_FOOTBALL_MATCHES_PLAYER_SCORE = 'ADD_FOOTBALL_MATCHES_PLAYER_SCORE';
export const ADD_CRICKET_MATCHES_PLAYER_SCORE = 'ADD_CRICKET_MATCHES_PLAYER_SCORE';

//get tournament by sport
export const GET_TOURNAMENT_BY_SPORT = 'GET_TOURNAMENT_BY_SPORT';
export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';

//create new tournament
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';

//set the sport
export const SET_SPORT = 'SET_SPORT';

export const SET_STANDING = 'SET_STANDING';
export const SET_GROUP = 'SET_GROUP';
export const ADD_TEAM_GROUP = 'ADD_TEAM_GROUP';
export const ADD_GROUP = 'ADD_TEAM_GROUP';

//club
export const CREATE_CLUB = 'CREATE_CLUB';
export const GET_CLUB = 'GET_CLUB';