export const SEND_OTP = 'SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const CREATE_USER = 'CREATE_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const SET_MOBILE_NUMBER_VERIFIED = 'SET_MOBILE_NUMBER_VERIFIED';