export const SEND_OTP = 'SEND_OTP';
export const VERIFY_OTP = 'VERIFY_OTP';
export const CREATE_USER = 'CREATE_USER';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_MOBILE_NUMBER = 'SET_MOBILE_NUMBER';
export const SET_MOBILE_NUMBER_VERIFIED = 'SET_MOBILE_NUMBER_VERIFIED';
export const SET_USER = 'SET_USER';
export const LOGOUT = 'LOGOUT';
export const CHECK_EXPIRE_TIME = 'CHECK_EXPIRE_TIME';
export const SET_LIKES = 'SET_LIKES';
export const SET_UNLINKES = 'SET_UNLINKES';
export const SET_COMMENT = 'SET_COMMENT';
export const SET_THREADS = 'SET_THREADS';
export const TOGGLE_LIKES = 'TOGGLE_LIKES';
export const SET_COMMENTS = 'SET_COMMENTS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const SET_COMMENT_TEXT = 'SET_COMMENT_TEXT';
export const ADD_THREADS = 'ADD_THREADS';
export const USER_PROFILE = 'USER_PROFILE';
export const IS_FOLLOWING = 'IS_FOLLOWING'
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_FOLLOWING_USER = 'GET_FOLLOWING_USER';
export const GET_FOLLOWER_USER = 'GET_FOLLOWER_USER';
export const GET_JOINED_COMMUNITY = 'JOINED_COMMUNITY';
export const GET_COMMUNITY = 'GET_COMMUNITY';
export const ADD_COMMUNITY = 'ADD_COMMUNITY';
export const ADD_JOINED_COMMUNITY = 'GET_JOINED_COMMUNITY';
export const SET_PROFILE_AVATAR = 'SET_PROFILE_AVATAR';
export const SET_EDIT_FULL_NAME = 'SET_EDIT_FULL_NAME';
export const SET_EDIT_DESCRIPTION = 'SET_EDIT_DESCRIPTION';
export const GET_PROFILE = 'GET_PROFILE';
//added create new community
//added match score
export const GET_CRICKET_MATCHES = 'GET_CRICKET_MATCHES';
export const GET_FOOTBALL_MATCHES = 'GET_FOOTBALL_MATCHES';
export const GET_CRICKET_PLAYER_SCORE = 'GET_CRICKET_PLAYER_SCORE';
export const GET_FOOTBALLL_PLAYER_SCORE = 'GET_FOOTBALLL_PLAYER_SCORE';
export const ADD_FOOTBALL_SCORE = 'ADD_FOOTBALL_SCORE';
export const SET_FOOTBALL_SCORE = 'SET_FOOTBALL_SCORE';
export const GET_FOOTBALL_SCORE = 'GET_FOOTBALL_SCORE';
export const ADD_CRICKET_SCORE = 'ADD_CRICKET_SCORE';
export const ADD_FOOTBALL_MATCHES_PLAYER_SCORE = 'ADD_FOOTBALL_MATCHES_PLAYER_SCORE';
export const ADD_CRICKET_MATCHES_PLAYER_SCORE = 'ADD_CRICKET_MATCHES_PLAYER_SCORE';

//get tournament by sport
export const GET_TOURNAMENT_BY_SPORT = 'GET_TOURNAMENT_BY_SPORT';
export const GET_TOURNAMENT_BY_ID = 'GET_TOURNAMENT_BY_ID';

//create new tournament
export const ADD_TOURNAMENT = 'ADD_TOURNAMENT';

//set the sport
export const SET_GAMES = 'SET_GAMES';

export const SET_STANDING = 'SET_STANDING';
export const SET_GROUP = 'SET_GROUP';
export const ADD_TEAM_GROUP = 'ADD_TEAM_GROUP';
export const ADD_GROUP = 'ADD_TEAM_GROUP';

//club
export const CREATE_CLUB = 'CREATE_CLUB';
export const GET_CLUB = 'GET_CLUB';

//set and get team
export const SET_TEAMS = 'SET_TEAMS';
export const GET_TEAMS = 'GET_TEAMS';

//set matches of sport
export const SET_MATCHES = 'SET_MATCHES';
export const GET_MATCHES = 'GET_MATCHES';
export const SET_MATCH_SUB_STATUS = 'SET_MATCH_SUB_STATUS';
export const GET_TEAMS_BY_SPORT = 'GET_TEAMS_BY_SPORT';

//set the current game of tournament or match or team
export const SET_GAME = 'SET_GAME';

export const GET_MATCH = 'GET_MATCH';

export const GET_TEAM_PLAYERS = 'GET_TEAM_PLAYERS';

export const SET_TEAM_PLAYER = 'SET_TEAM_PLAYER';

export const GET_CRICKET_BATTING_SCORE = 'GET_CRICKET_BATTING_SCORE';
export const GET_CRICKET_BOWLING_SCORE = 'GET_CRICKET_BOWLING_SCORE';
export const GET_CRICKET_WICKET_FALLEN = 'GET_CRICKET_WICKET_FALLEN';
export const GET_CRICKET_INNING_SCORE = 'GET_CRICKET_INNING_SCORE';
export const ADD_BATSMAN = 'ADD_BATSMAN';
export const ADD_BOWLER = 'ADD_BOWLER';
export const UPDATE_BATSMAN_SCORE = 'UPDATE_BATSMAN_SCORE';
export const UPDATE_BOWLER_SCORE = 'UPDATE_BOWLER_SCORE';
export const UPDATE_INNING_SCORE = 'UPDATE_INNING_SCORE';
export const ADD_CRICKET_WICKET_FALLEN = 'ADD_CRICKET_WICKET_FALLEN';

export const SET_CRICKET_TOSS = 'SET_CRICKET_TOSS';

export const SET_BAT_TEAM = 'SET_BAT_TEAM';

export const GET_HOME_PLAYER = 'GET_HOME_PLAYER';
export const GET_AWAY_PLAYER = 'GET_AWAY_PLAYER';

export const SET_END_INNING = 'SET_END_INNING';

export const SET_CURRENT_INNING = 'SET_CURRENT_INNING';
export const SET_INNING_STATUS = 'SET_INNING_STATUS';
export const SET_CURRENT_INNING_NUMBER = 'SET_CURRENT_INNING_NUMBER';
export const SET_INNING_COMPLETED = 'SET_INNING_COMPLETED';
export const SET_MATCH_FORMAT = 'SET_MATCH_FORMAT';

export const GET_CRICKET_MATCH_SQUAD = 'GET_CRICKET_MATCH_SQUAD';
export const SET_CRICKET_MATCH_SQUAD = 'SET_CRICKET_MATCH_SQUAD';

export const SET_AUTH_PROFILE_PUBLIC_ID = 'SET_AUTH_PROFILE_PUBLIC_ID';

export const ADD_TOURNAMENT_ENTITIES = 'ADD_TOURNAMENT_ENTITIES';
export const GET_TOURNAMENT_ENTITIES = 'GET_TOURNAMENT_ENTITIES';
export const SET_CURRENT_BATSMAN = 'SET_CURRENT_BATSMAN';
export const SET_CURRENT_BOWLER = 'SET_CURRENT_BOWLER';
export const INITIALIZE_NEW_INNING = 'INITIALIZE_NEW_INNING';

export const ADD_FOOTBALL_INCIDENT = 'ADD_FOOTBALL_INCIDENT';
export const RESET_FOOTBALL_INCIDENTS = 'RESET_FOOTBALL_INCIDENTS';
export const GET_FOOTBALL_INCIDENTS = 'GET_FOOTBALL_INCIDENTS';

export const SET_MATCH_STATUS = 'SET_MATCH_STATUS';

// Validation action types
export const SET_VALIDATION_ERROR = 'SET_VALIDATION_ERROR';
export const CLEAR_VALIDATION_ERROR = 'CLEAR_VALIDATION_ERROR';
export const CLEAR_FORM_VALIDATION_ERRORS = 'CLEAR_FORM_VALIDATION_ERRORS';
export const CLEAR_ALL_VALIDATION_ERRORS = 'CLEAR_ALL_VALIDATION_ERRORS';

// Loading state action types
export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';
export const CLEAR_ALL_LOADING = 'CLEAR_ALL_LOADING';